Fiap.Aula03.Web.Exemplo/Models/Endereco.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Models
{
    [Table("Tbl_Endereco")]
    public class Endereco
    {
        [Column("Id"), HiddenInput]
        public int EnderecoId { get; set; }

        public string Logradouro { get; set; }

        public string Cep { get; set; }


    }
}

Fiap.Aula03.Web.Exemplo/Models/ErrorViewModel.cs
using System;

namespace Fiap.Aula03.Web.Exemplo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Fiap.Aula03.Web.Exemplo/Models/Jogador.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Models
{
    [Table("Tbl_Jogador")]
    public class Jogador
    {
        [Column("Id"), HiddenInput]
        public int JogadorId { get; set; }

        public string Nome { get; set; }

        [Required]
        public string NickName { get; set; }

        public int Conquistas { get; set; }

        public Genero Genero { get; set; }

        //N:M
        public ICollection<JogoJogador> JogoJogadores { get; set; }

    }

    public enum Genero
    {
        Masculino, Feminino
    }
}

Fiap.Aula03.Web.Exemplo/Models/Jogo.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Models
{
    [Table("Tbl_Jogo")]
    public class Jogo
    {
        [Column("Id"), HiddenInput]
        public int JogoId { get; set; }
        //Maximo caracteres "MaxLength()"
        [Required, MaxLength(80)]
        public string Nome { get; set; }

        //N:1
        public Produtora Produtora { get; set; }

        public int? ProdutoraId { get; set; }

        public bool? Multiplataforma { get; set; }
        [Required]
        public Plataforma Plataforma { get; set; }

        [DataType(DataType.Date)] [Display(Name = "Data Lançamento")]
        [Column("Data_Lancamento")]
        public DateTime? DataLancamento { get; set; }
        public decimal? Valor { get; set; }

        //N:M
        public ICollection<JogoJogador> JogoJogadores { get; set; }

    }

    public enum Plataforma 
    {
        Pc, Mobile, Xbox, Playstation
    }


}

Fiap.Aula03.Web.Exemplo/Models/JogoJogador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Models
{
    //Classe que mapeia a tabela associativa
    [Table("Tbl_Jogo_Jogador")]
    public class JogoJogador
    {

        public Jogo Jogo { get; set; }

        public int JogoId { get; set; }

        public Jogador Jogador { get; set; }

        public int JogadorId { get; set; }

    }
}

Fiap.Aula03.Web.Exemplo/Models/Produtora.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Models
{
    [Table("Tbl_Produtora")]
    public class Produtora
    {

        [Column("Id"), HiddenInput]
        public int ProdutoraId { get; set; }

        public string Nome { get; set; }

        [DataType(DataType.Date)][Display(Name = "Data Fundação")]
        public DateTime DataFundacao { get; set; }
        
        //1:N
        public virtual ICollection<Jogo> Jogos { get; set; }

        //1:1
        public Endereco Endereco { get; set; }

        public int EnderecoId { get; set; }

    }
}

Fiap.Aula03.Web.Exemplo/Controllers/HomeController.cs
using Fiap.Aula03.Web.Exemplo.Models;
using Fiap.Aula03.Web.Exemplo.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private FiapGamesContext _context; 

        public HomeController(ILogger<HomeController> logger, FiapGamesContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewData["jogos"] = _context.Jogos.Count(); // retorna a quantidade de jogadores cadastrados
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fiap.Aula03.Web.Exemplo/Controllers/JogoController.cs
using Fiap.Aula03.Web.Exemplo.Models;
using Fiap.Aula03.Web.Exemplo.Persistencia;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Controllers
{
    public class JogoController : Controller
    {
        private FiapGamesContext _context;

        //Receber o context por injeção de dependencia no construtor

        public JogoController(FiapGamesContext context)
        {
            _context = context;
        }

        //? -> permite atribuir null
        public IActionResult Index(string nomeBusca, Plataforma? plataforma)
        {
            return View(_context.Jogos.Where(j =>
                (j.Nome.Contains(nomeBusca) || nomeBusca == null) && 
                (j.Plataforma == plataforma || plataforma == null)).ToList());
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Jogo jogo)
        {
            _context.Jogos.Add(jogo);
            _context.SaveChanges();
            TempData["Cadastrado"] = "Jogo Cadastrado!!";
            return RedirectToAction("Cadastrar");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var jogo = _context.Jogos.Find(id);
            return View(jogo);
        }

        [HttpPost]
        public IActionResult Editar(Jogo jogo)
        {
            _context.Jogos.Update(jogo);
            _context.SaveChanges();
            TempData["Alterado"] = "Jogo Alterado!!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remover(int id)
        {
            var jogo = _context.Jogos.Find(id);
            _context.Jogos.Remove(jogo);
            _context.SaveChanges();
            TempData["Removido"] = "Jogo Removido!!";
            return RedirectToAction("Index");
        }





    }
}

Fiap.Aula03.Web.Exemplo/Controllers/ProdutoraController.cs
using Fiap.Aula03.Web.Exemplo.Models;
using Fiap.Aula03.Web.Exemplo.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Aula03.Web.Exemplo.Controllers
{
    public class ProdutoraController : Controller
    {

        private FiapGamesContext _context;


        public ProdutoraController(FiapGamesContext context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Cadastrar(Produtora produtora)
        {
            _context.Produtoras.Add(produtora);
            _context.SaveChanges();
            TempData["msg"] = "Produtora cadastrada com sucesso";
            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            return View(_context.Produtoras.Include(p => p.Endereco).ToList());
        }
    }
}

Fiap.Aula03.Web.Exemplo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">Jogos Registrados</h5>
        <h6 class="card-subtitle mb-2 text-muted">Total</h6>
        <p class="card-text">@ViewData["jogos"]</p>
        <a asp-action="cadastrar" asp-controller="jogo" class="card-link">Cadastrar</a>
        <a asp-action="index" asp-controller="jogo" class="card-link">Listar</a>
    </div>
</div>

Fiap.Aula03.Web.Exemplo/Views/Jogo/Cadastrar.cshtml
@model Jogo
@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar Jogo</h1>

<mensagem texto ="@TempData["Cadastrado"]" ></mensagem>

<form asp-action="Cadastrar" >

    <partial name="_Form" />

    <input type="submit" value="Cadastrar" class="btn btn-primary" />

    <a class="btn btn-danger" asp-controller="jogo" asp-action="index">Listar</a>

</form>

Fiap.Aula03.Web.Exemplo/Views/Jogo/Editar.cshtml
@model Jogo 

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<form asp-action="Editar">

    <input asp-for="JogoId" />

    <partial name="_Form" />

    <input type="submit" value="Editar" class="btn btn-primary" />

    <a class="btn btn-danger" asp-controller="jogo" asp-action="index">Listar</a>

</form>

Fiap.Aula03.Web.Exemplo/Views/Jogo/Index.cshtml
@model List<Jogo>

@{
    ViewData["Title"] = "Index";
}

<h1>Jogos</h1>

<form class="form-inline mb-3">
    <input type="text" name="nomeBusca" class="form-control mr-2" placeholder="Digite o nome" />
    <select class="form-control mr-2" asp-items="@Html.GetEnumSelectList<Plataforma>()" name="plataforma" >
        <option>Plataforma</option>
    </select> 
    <input type="submit" value="Pesquisar" class="btn btn-success" />
</form>

<mensagem texto="@TempData["Alterado"]"></mensagem>

<mensagem texto="@TempData["Removido"]"></mensagem>

@if ( Model.Count == 0)
{
    <mensagem texto="Nenhum Registro encontrado" class="alert alert-danger"></mensagem>
}

<table class="table table-borderless">

    <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Lançamento</th>
        <th>Plataforma</th>
        <th>Multiplataforma</th>
        <th>Valor</th>
        <th></th>
    </tr>

    @foreach (var j in Model)
    {
        <tr>
            <td>@j.JogoId</td>
            <td>@j.Nome</td>
            <td>@j.DataLancamento.GetValueOrDefault().ToShortDateString()</td>
            <td>@j.Plataforma</td>
            <td>@(j.Multiplataforma.GetValueOrDefault()?"Sim":"Não")</td>
            <td>@j.Valor.GetValueOrDefault().ToString("n")</td>

            <td>
                <a asp-action="editar" asp-route-id="@j.JogoId" class="btn btn-dark btn-sm">Editar</a>
                <!--Ao clicar no botao o codigo do pedido é enviado ao campo oculato do form do modal-->
                <button onclick="idJogo.value = @j.JogoId" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                    Remover
                </button>
            </td>
        </tr>
    }


</table>

<a class="btn btn-outline-primary" asp-action="Cadastrar" asp-controller="Jogo">New Jogo</a>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente remover o jogo?
            </div>
            <div class="modal-footer">
                <form asp-action="Remover">
                    <input type="hidden" name="id" id="idJogo" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

Fiap.Aula03.Web.Exemplo/Views/Jogo/_Form.cshtml
@model Jogo


<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
</div>

<div class="form-group">
    <label asp-for="Plataforma"></label>
    <select asp-items="@Html.GetEnumSelectList<Plataforma>()" asp-for="Plataforma" class="form-control">
        <option>Selecione</option>
    </select>
</div>

<div class="form-group">
    <input asp-for="Multiplataforma" />
    <label asp-for="Multiplataforma"></label>
</div>

<div class="form-group">
    <label asp-for="DataLancamento"></label>
    <input asp-for="DataLancamento" class="form-control" />
</div>

<div class="form-group">
    <label asp-for="Valor"></label>
    <input asp-for="Valor" class="form-control" />
</div>

Fiap.Aula03.Web.Exemplo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap Games</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap Games</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Jogos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Jogo" asp-action="index">Listar</a>
                                <a class="dropdown-item" asp-controller="Jogo" asp-action="cadastrar">Cadastrar</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Produtoras
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Produtora" asp-action="index">Listar</a>
                                <a class="dropdown-item" asp-controller="Produtora" asp-action="cadastrar">Cadastrar</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Fiap.Aula03.Web.Exemplo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>